### ISSUE TITLE
Is the source for the onerng package available in github?

### ISSUE THREAD

**Issue by hairyhenderson** [OneRNG/onerng.github.io#2]
Hi @jimcheetham - I see a bunch of binaries being distributed in https://github.com/OneRNG/onerng.github.io/tree/master/sw/ but I can't seem to figure out where the  upstream source repository lives, or even if one exists... Does it? If so, perhaps the link could be made more clear in the documentation :)

Just ordered a OneRNG so I'm mostly just curious at this point to dig through revision history.

Thank you!

**Comment by jimcheetham** [comment]
This repository is the website itself, not the "code" of OneRNG, and as such it publishes binaries of things rather their history, as you've seen.

https://github.com/OneRNG/hardware and https://github.com/OneRNG/firmware might be more what you are looking for.

http://moonbaseotago.com/onerng/ has a changelist that summarises the reasons for each version, but the other component of the software collection - the OS userspace code - is basically just a set of convenience scripts rather than anything related to how the device itself functions, and we haven't formally published the history of those, just the releases.

Further questions are probably better off asked via the discussion group (http://lists.onerng.info/groups/onerng-talk/) so more people can see the answers :-)

**Comment by hairyhenderson** [comment]
Thanks @jimcheetham - I saw the `hardware` and `firmware` repos. The convenience scripts were what I was looking for however. Would be nice if you would consider putting those into GitHub too 🙂
